storyprotocol/protocol-core-v1

- contracts/interfaces/modules/royalty/policies/IAncestorsVaultLAP.sol
- contracts/interfaces/modules/royalty/policies/IRoyaltyPolicyLAP.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/AncestorsVaultLAP.sol
- contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
- script/foundry/deployment/Main.s.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/modules/royalty/AncestorsVaultLAP.t.sol
- test/foundry/modules/royalty/RoyaltyPolicyLAP.t.sol
This pr makes 3 adjustments to the LAP royalty policy:
- Does a minor fix the event PolicyInitialized
- Changes the receiver of the RNFTs present the ancestors vault to being the IPAccount (vs the IP Pool) to significantly simplify the royalty claiming process
- Removes ETH claiming from the codebase to simplify the code given it is not supported for payment and therefore was not being used
> Simplify royalty logic

- contracts/interfaces/modules/royalty/policies/IAncestorsVaultLAP.sol
- contracts/interfaces/modules/royalty/policies/IRoyaltyPolicyLAP.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/AncestorsVaultLAP.sol
- contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
- script/foundry/deployment/Main.s.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/integration/flows/disputes/Disputes.t.sol
- test/foundry/integration/flows/licensing/LicensingScenarios.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/modules/royalty/AncestorsVaultLAP.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/modules/royalty/RoyaltyPolicyLAP.t.sol
This pr:
- Removes ancestors hash from LAP royalty policy
- Removes the requirement royalty context from LAP royalty policy
The goal of the changes is to greatly improve integrability as external projects no longer need to request the SDK to obtain the royaltyContext input when setting up a royalty policy. Gas increased by around 50% as previously discussed for initPolicy. Developer experience and ease of setup are greatly improved as there is no need to retrieve and understand the previously existing royalty context data struct.
> Remove ancestors hash and royalty context requirement from royalty LAP policy

- .github/workflows/test.yml
- script/foundry/deployment/Main.s.sol
- test/foundry/mocks/registry/MockLicenseRegistryV2.sol
- test/foundry/utils/DeployHelper.t.sol
- test/foundry/utils/TestProxyHelper.sol
Temporarily remove OZ upgrades foundry lib install from GHA workflow.
> Remove oz storage checks from GHA

- contracts/interfaces/registries/IIPAssetRegistry.sol
- contracts/lib/Errors.sol
- contracts/registries/IPAssetRegistry.sol
- contracts/utils/ShortStringOps.sol
- test/foundry/mocks/token/MockERC721WithoutMetadata.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR introduces an enhancement to the IP registration process within the Story Protocol by implementing permissionless IP registration. With this update, the IPAssetRegistry now automatically retrieves the required metadata ("name" and "tokenURI") from the IP NFT, eliminating the need for registrants or callers to provide this metadata manually. 
It allows anyone can register IP for any NFT permissionlessly.
Additionally, IPAccounts are deployed automatically during the IP registration process, with metadata being stored directly into the IPAccount. This simplification not only streamlines the registration process but also reduces the gas costs on-board IPs into the Story Protocol. 
It's important to note that while this PR enables permissionless IP registration, it does not remove the …
> Implement Permissionless IP Registration

- .github/workflows/test.yml
Some notes:
add job timestamp
pinpoint checkout version
remove junk code (list files, print out env variables, not being used jobs ...)
remove unnecessary env variables in the workflow
> [feat] optimize the CI workflow

- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR ensures that a child IP cannot link to more parent IPs again. Added validation logic in the IP linking function to check if the child IP is already associated with a parent IP. If so, the operation is aborted, and an error message is returned.
> Prevent Child IP from Linking to More Parent IPs More than Once

- contracts/interfaces/modules/royalty/IRoyaltyModule.sol
- contracts/interfaces/modules/royalty/policies/IRoyaltyPolicyLAP.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/DisputeModule.sol
- contracts/modules/royalty/RoyaltyModule.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
- script/foundry/deployment/Main.s.sol
- test/foundry/mocks/module/MockRoyaltyModule.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/utils/BaseTest.t.sol
- test/foundry/utils/DeployHelper.t.sol
This pr adds royalty related restrictions when IP assets are tagged via dispute:
- tagged IP assets are unable to receive license minting fee
- tagged IP assets are unable to receive voluntary royalty payments
- tagged IP assets IpRoyaltyVault does not allow claiming revenue tokens nor collect of royalty tokens
> Dispute effects on royalty

- contracts/registries/IPAccountRegistry.sol
Makes IPAccountRegistry abstract, since we intend to use it for inheritance by IPAssetRegistry.
Closes #54
> Abstract IPAccountRegistry

- contracts/lib/Errors.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR detects duplicate license terms when registering derivative and revert operations.
Closes #41
> Detect and Revert Duplicate License Terms

- contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/RoyaltyModule.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/modules/royalty/RoyaltyPolicyLAP.t.sol
Royalty Fixes that were previously in PR60
> Royalty fixes

- contracts/LicenseToken.sol
- contracts/access/AccessController.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/DisputeModule.sol
- contracts/modules/dispute/policies/ArbitrationPolicySP.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/royalty/RoyaltyModule.sol
- contracts/registries/IPAccountRegistry.sol
- contracts/registries/IPAssetRegistry.sol
- contracts/registries/LicenseRegistry.sol
- contracts/registries/ModuleRegistry.sol
- script/foundry/utils/DeployHelper.sol
- script/foundry/utils/upgrades/ERC7201Helper.s.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
Refactor to make IPAssetRegistry upgradeable
> Upgradeable IpAssetRegistry

- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces the isExpiredNow function to the LicenseRegistry. This function checks the current expiration time of an IP and determines if it has expired based on the system's current time. This change is to address the requirements outlined in issue #68.
> Add `isExpiredNow` Function to LicenseRegistry

- contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
- script/foundry/utils/DeployHelper.sol
- script/foundry/utils/upgrades/ERC7201Helper.s.sol
- test/foundry/mocks/module/MockIpRoyaltyVaultV2.sol
- test/foundry/upgrades/IPRoyaltyVaults.t.sol
Although the royalty vault's beacon was already upgradeable by AccessManager contract (since it was the original admin), we are doing the following to make the process more consistent with the rest of `UPGRADER_ROLE` reserved methods
- Add method to upgrade royalty vaults in RoyaltyPolicyLAP, `restricted`
- Transfer ownership of the vault to RoyaltyPolicyLAP in `DeployHelper`
- Set the new method to be called by `UPGRADER_ROLE` like the others.
- Test it
Closes #49
> Upgrade beacon through RoyaltyPolicyLAP

- contracts/interfaces/registries/IIPAssetRegistry.sol
- contracts/lib/Errors.sol
- contracts/registries/IPAssetRegistry.sol
- test/foundry/integration/BaseIntegration.t.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/modules/dispute/ArbitrationPolicySP.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/modules/metadata/CoreMetadataModule.t.sol
- test/foundry/modules/metadata/CoreMetadataViewModule.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/registries/IPAssetRegistry.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces a new function to the `IPAssetRegistry` contract that allows for the registration of IP NFTs from different chain. 
The new function, `registerCrossChain`, takes in three parameters: `chainId`, `tokenContract`, and `tokenId`. The `chainId` represents the identifier of the blockchain network where the IP NFT resides. 
This function first checks if the `chainId` is the same as the current network's `chainId`. If they are the same, it throws an error as this function is specifically designed for cross-chain registrations.
> Add Cross-Chain IP  Registration Functionality 

- .github/workflows/foundry_ci.yml
- README.md
- foundry.toml
So that running `forge test` won't recompile all the files.
> Move build-info into just the CI, for faster recompiles

- contracts/interfaces/modules/licensing/ILicenseTemplate.sol
- contracts/interfaces/modules/licensing/IPILicenseTemplate.sol
- contracts/lib/PILFlavors.sol
- contracts/modules/licensing/PILicenseTemplate.sol
- test/foundry/access/AccessController.t.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/mocks/module/MockLicenseTemplate.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/utils/LicensingHelper.t.sol
This PR introduces a new field, `uri`, into the PILTerms struct. This field is designed to hold a URI that points to offchain Programable IP License terms.
Closes #77
> Add Offchain URI Field to PILTerms

- contracts/interfaces/modules/dispute/policies/IArbitrationPolicy.sol
- contracts/interfaces/modules/royalty/IRoyaltyModule.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/policies/ArbitrationPolicySP.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/royalty/RoyaltyModule.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
Makes royalty payments revert if the ip is expired.
This change is part of the issue https://github.com/storyprotocol/protocol-core-v1/issues/68.
> Add expiration restriction to royalty payments

- package.json
- remappings.txt
- script/foundry/utils/DeployHelper.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
This PR introduces an enhancement to our deployment process with the introduction of `CREATE3`. Here's a brief overview of the changes:
1. **Introduction of `CREATE3`:** We have introduced `CREATE3`, a feature that allows deployment to a deterministic address using only a salt. This is a major advancement in resolving cyclical dependencies within our system. 
2. **Immutable Addresses for Dependencies:** The introduction of `CREATE3` allows us to store dependencies as immutable addresses. This eliminates the need for governed functions to set these addresses, further simplifying our protocol.
3. **Simplified Protocol Post Configurations:**  No need to configure dependencies' addresses through the governance process after deployment.
> Introduction of CREATE3 for Deployment to Deterministic Addresses to Resolve Cyclical Dependencies 

- contracts/access/AccessController.sol
Maintaining the same logic, we can reorder the code to:
- Revert/return early
- Reduce if nesting
> Flatten if structure in `checkPermissions`

- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- yarn.lock
Relates to issue https://github.com/storyprotocol/protocol-core-v1/issues/100
Makes timestamp a uint40.
> Gas optimization in IpRoyaltyVault

- contracts/LicenseToken.sol
- contracts/interfaces/ILicenseToken.sol
- contracts/lib/Errors.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This RP includes changes that remove the expiry from the license token. The concept of expiry was initially introduced to provide a time limit for the validity of a license token. However, after careful consideration and review, we have decided to remove this feature to simplify the licensing process License Token benefit liquidity.
Update Uint Test according the change.
Closes #117
> Remove Expiry from License Token

- contracts/LicenseToken.sol
- contracts/access/AccessController.sol
- contracts/interfaces/ILicenseToken.sol
- contracts/interfaces/modules/royalty/IRoyaltyModule.sol
- contracts/lib/Errors.sol
- contracts/lib/PILicenseTemplateErrors.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/licensing/PILicenseTemplate.sol
- contracts/modules/royalty/RoyaltyModule.sol
- contracts/registries/LicenseRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/LicenseToken.t.sol
- test/foundry/mocks/module/MockAccessControllerV2.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
- test/foundry/upgrades/Upgrades.t.sol
- test/foundry/utils/Create3Deployer.sol
- test/foundry/utils/TestProxyHelper.sol
This PR introduces the use of `CREATE3` for deploying our smart contracts, an update aimed at resolving the challenges posed by cyclical dependencies during the deployment phase. By leveraging CREATE3, we can deploy contracts to deterministic addresses using a predefined salt. This approach has several advantages and key implementations as detailed below:
1. **Deterministic Deployment:** Utilize CREATE3 to ensure all contracts with cyclical dependencies are deployed to known, deterministic addresses. This method uses only a salt for address derivation, making the process more predictable and secure.
2. **Immutable Storage:** By directly passing these deterministic addresses to the constructors of dependent contracts, we can store them as immutable variables within the contracts. This not …
> Deploy with CREATE3 for Deterministic Addresses to Resolve Cyclical Dependencies in Contract Deployment

- contracts/access/AccessController.sol
- contracts/interfaces/access/IAccessController.sol
- contracts/lib/Errors.sol
- test/foundry/access/AccessController.t.sol
This PR introduces a new method, `setAllPermissions`, to the AccessController. The existing setPermission function provides comprehensive functionality with the capability to set permissions at a granular level.
The new `setAllPermissions` function simplifies permission settings by reducing the parameters required, focusing solely on full permissions across all modules and functions. This method is designed to be user-friendly and reduces the risk of configuration errors, making it ideal for scenarios where complete delegation of control is necessary. 
1. **Introduction of `setAllPermissions` Function:** Allows users to grant all permissions associated with an `IPAccount` to another address (signer) through a straightforward interface, using only three parameters: the `IPAccount` address, …
> Enhance Permission Management with Simplified `setAllPermissions` Method in AccessController

- contracts/lib/ExpiringOps.sol
- contracts/modules/licensing/PILicenseTemplate.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR addresses the issue where the expiration time of a Child IP could exceed the expiration time of its Parent IP, which contradicts the intended inheritance of expiration constraints from parent to derivative IPs.
- Modified the derivative registration logic to ensure that the expiration time of the Child IP is either equal to or earlier than that of the Parent IP.
- Updated tests to include scenarios where the Parent IP has a shorter expiration time than the license terms to which a Child IP registers.
Closes #128
> Expiration Time for Child IPs Not Exceed Parent IP

- contracts/modules/licensing/PILicenseTemplate.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
This PR includes changes that enhance the `PILicenseTemplate` contract. The contract now checks whether the input `licenseTermsId` exists when performing verification during the minting of a license token.
Modified the `PILicenseTemplate` contract to include a check for the existence of licenseTermsId. If the licenseTermsId does not exist, the contract will revert and prevent the minting of the license token.
Updated the unit tests to cover the code change in this PR.
> Add Existence Check for `licenseTermsId` when verifyMintLicenseToken in PILicenseTemplate

- contracts/interfaces/modules/dispute/policies/IArbitrationPolicy.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/policies/ArbitrationPolicySP.sol
- script/foundry/deployment/Main.s.sol
- script/foundry/utils/DeployHelper.sol
- script/foundry/utils/upgrades/ERC7201Helper.s.sol
- test/foundry/modules/dispute/ArbitrationPolicySP.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/utils/BaseTest.t.sol
Removes the `governanceWithdraw` function and replaces its functionality with a transfer directly to a treasury address whenever a dispute judgement tags an IP as infringing.
> Fix governance withdraw

- contracts/modules/licensing/LicensingModule.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
Added `whenNotPaused` modifier to `setLicensingConfig` method
> v1.1 TRST-L-1 User can set undesired module as hook when contract is paused for maintenance

- contracts/pause/ProtocolPauseAdmin.sol
- test/foundry/pause/ProtocolPauseAdmin.t.sol
Return false in `ProtocolPauseAdmin.isAllProtocolPaused()` when there is no pausable contracts added.
```test_ProtocolPauseAdmin_notPaused_ifNoPausables```
>  isAllProtocolPaused returns true even when there are not pausables configured

- contracts/interfaces/registries/IIPAccountRegistry.sol
- contracts/registries/IPAccountRegistry.sol
- contracts/registries/IPAssetRegistry.sol
- test/foundry/IPAccount.t.sol
- test/foundry/IPAccountImpl.btt.t.sol
- test/foundry/IPAccountMetaTx.t.sol
- test/foundry/IPAccountStorage.t.sol
- test/foundry/IPAccountStorageOps.t.sol
- test/foundry/access/AccessControlled.t.sol
- test/foundry/access/AccessController.t.sol
- test/foundry/modules/external/TokenWithdrawalModule.t.sol
- test/foundry/modules/metadata/CoreMetadataViewModule.t.sol
- test/foundry/modules/metadata/MetadataModule.t.sol
- test/foundry/registries/IPAccountRegistry.t.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR includes changes that refactor the `registerIpAccount` function in the `IPAccountRegistry` contract. The function has been made internal to ensure there is only one unique way to register an IPAccount, which is through the `IPAssetRegistry`. This change is aimed at making the IP Asset registration path more consistent.
1. Modified the `registerIpAccount` function in the `IPAccountRegistry` contract to be internal. This change ensures that IP Account registration can only be done through the `IPAssetRegistry`, providing a single, consistent path for IP registration.
2. Updated the unit tests to reflect these changes. 
3. Updated the NatSpec documentation to reflect these changes.
Updated the unit test case cover the code changes.
> Refactor `registerIpAccount` to be Internal function

- contracts/lib/Errors.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR includes changes that enhance the `registerDerivativeIp` function in the `LicenseRegistry` contract. The function now checks whether the child IP already has a child IP before registering it as a derivative. This change is aimed at preventing recursive derivatives in our IP registration process.
1. Modified the `registerDerivativeIp` function to include a check for existing child IPs. If the child IP already has a child IP, the function will revert and prevent the registration.
2. Updated the unit tests to reflect these changes. 
Add unit tests to cover to new code changes
> Prevent Recursive Derivatives in IP Registration

- contracts/LicenseToken.sol
This PR merges the `LicensorStorage` struct into the `LicenseTokenStorage` struct within the `LicenseToken` contract. This change aims to simplify the code by consolidating storage structures.
- **Merged Structs**: Combined the `LicensorStorage` struct into the `LicenseTokenStorage` struct.
> Merge LicensorStorage into LicenseTokenStorage to Simplify Code

- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/mocks/grouping/MockEvenSplitGroupPool.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
This PR adds integration tests for the Grouping Module with the Royalty Modules. These tests ensure that the Grouping Module correctly interacts with the Royalty Modules, verifying the functionality of creating groups, adding IPs to groups, registering derivatives, paying royalties, and distributing rewards.
- **Integration Tests**: Added integration tests for the Grouping Module with the Royalty Modules.
- **Test Scenarios**: Covered scenarios including group creation, IP addition, derivative registration, royalty payment, and reward distribution.
> Add Integration Tests for Grouping Module with Royalty Modules

- script/foundry/utils/DeployHelper.sol
This PR changes the default ERC20 token used in the project to a new address of Story USD (SUSD) on public testnet (chainid 1513).  Allowing it to be used for royalty payments.
- **Default Currency Update**: Changed the default ERC20 token to Story USD (SUSD).
> Change Default Currency ERC20 Token to Story USD (SUSD) on Public Testnet

- contracts/registries/LicenseRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/integration/flows/disputes/Disputes.t.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/integration/flows/licensing/LicensingScenarios.t.sol
- test/foundry/invariants/LicensingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR configures the non-commercial remix license as the default license in the deployment script as license terms ID 1, ensuring that the default license terms are set during the deployment of protocol contracts. Additionally, it updates the License Registry API to handle the default license terms consistently.
- **Deployment Script Update**: Configured the non-commercial remixable license as the default license.
- **API Consistency**: Updated the License Registry API to handle the default license terms consistently:
1. `getAttachedLicenseTerms()`: Default license terms will be the last one attached to the IP.
2. `getAttachedLicenseTermsCount()`: Default license terms are also counted.
3. `hasIpAttachedLicenseTerms()`: Default license terms are considered attached to the IP.
- **Set …
> Configure Non-Commercial Remix License as Default License in Deployment Script and Ensure Consistent API Behavior

- contracts/GroupNFT.sol
This PR changes the qualified caller of the `GroupNFT` contract from `IPAssetRegistry` to `GroupingModule`. This change ensures consistency with the deployment script, which passes the `GroupingModule` address to initialize the `GroupNFT`.
> Change Qualified Caller of GroupNFT from IPAssetRegistry to GroupingModule

- contracts/GroupNFT.sol
- contracts/lib/Errors.sol
Quick fix the error message in GroupNFT for checking caller is not GroupingModule.
> Fix error message of GroupNFT when caller is not GroupingModule

- contracts/GroupNFT.sol
- script/foundry/utils/DeployHelper.sol
Changes to `DeployHelper`
- Missing `addPausable` calls to `protocolPauser` for `RoyaltyPolicyLRP` and `GroupingModule`
- Missing `setTargetFunctionRole` calls for `RoyaltyPolicyLRP` and `GroupingModule`, used to set the UPGRADER role (with upgrade delay), andPAUSER role.
Tested deploy script locally
> Missing configs for new modules

- contracts/interfaces/modules/licensing/ILicensingHook.sol
- contracts/interfaces/modules/licensing/ILicensingModule.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/mocks/module/MockLicensingHook.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR introduces a new function to the Licensing Module that allows users to predict the minting fee for a given license and IP. This enhancement provides better transparency and planning for users by allowing them to estimate the costs associated with minting license tokens.
- **New Function**: Added a function to predict the minting fee for a given license and IP.
This enhancement is part of our ongoing efforts to improve the functionality and user experience of the Licensing Module.
Closes #240
> Add Function to Predict License Minting Fee in Licensing Module

- contracts/interfaces/modules/royalty/IRoyaltyModule.sol
- contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/RoyaltyModule.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/invariants/IpRoyaltyVault.t.sol
- test/foundry/mocks/grouping/MockEvenSplitGroupPool.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
This PR allows the revenue token claiming to be done on behalf of the claimer. Necessary, for example, for SPG to claim on behalf of royalty token holders.
> Allow revenue token claiming to be done on behalf of the claimer

- .github/workflows/foundry_ci.yml
Not trigger the invariant tests for pre-commit test as it is too slow.
> Disable fuzz test in GHA

- Makefile
Support generating GroupingModule ABI within Make
> Add GroupingModule to ABI generating command

- script/foundry/deployment/Main.s.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/mocks/token/SUSD.sol
This PR ensure deploy IPGraphACL to the predefined the address if IPGraphACL not yet deployed otherwise ignore deployment of IPGraphACL. 
Also set default CREATE3 seed to 6 which used to deployed the IPGraphACL
> Deploy IPGraphACL to predefined address if not yet deployed

- contracts/lib/Errors.sol
- contracts/modules/grouping/EvenSplitGroupPool.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR adds the Even Split Group Pool to the core protocol. This is the native Group Pool implementation designed to support the splitting of rewards among member IPAs of a Group IPA.
- **Even Split Group Pool Implementation**: Introduced the `EvenSplitGroupPool` contract to handle the distribution of rewards evenly among member IPAs of a Group IPA.
> Add Even Split Group Pool to Core Protocol

- contracts/interfaces/modules/grouping/IGroupRewardPool.sol
- contracts/interfaces/modules/grouping/IGroupingModule.sol
- contracts/interfaces/registries/IGroupIPAssetRegistry.sol
- contracts/lib/Errors.sol
- contracts/modules/grouping/EvenSplitGroupPool.sol
- contracts/modules/grouping/GroupingModule.sol
- contracts/registries/GroupIPAssetRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
Per off line discussion, we decide to move collectRoyalties to groupingModule from the EvenSplitPool and allow pass snapshots, so that group pool has an unified entry point of grouping operations. Also added a new function for check whether an address is whitelisted group reward pool.
> Refactor EvenSplitPool that Moving collectRoyalties  Function to GroupingModule 

- contracts/modules/grouping/EvenSplitGroupPool.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
This PR updates the `distributeRewards` function in the `EvenSplitGroupPool` contract to add a restriction that only allows the Grouping Module to call this function. This ensures that only authorized modules can distribute rewards, enhancing the security and integrity of the reward distribution process.
- **Function Restriction**: Added a restriction to the `distributeRewards` function to ensure it can only be called by the Grouping Module.
> Restrict distributeRewards Function to Grouping Module in EvenSplitGroupPool

- contracts/interfaces/registries/IIPAssetRegistry.sol
- contracts/lib/Errors.sol
- contracts/registries/IPAssetRegistry.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR introduces an IP Registration Fee Switch that allows the protocol to charge an IP registration fee in the future through a governance process. A governance function is added to set the Treasury Address that will receive the fee, specify an ERC20 token as the fee token, and set the fee amount. Currently, the fee amount is set to zero by default.
- **IP Registration Fee Switch**: Added functionality to enable charging an IP registration fee.
- **Governance Controls**: Added governance functions to set the Treasury Address, ERC20 fee token, and fee amount.
- **Gas Optimization**: Used `uint96` for the fee amount to save storage gas costs.
- **Enable Future Fee Charging**: Allow the protocol to charge an IP registration fee through governance.
- **Governance Management**: Provide …
> Introduce IP Registration Fee Switch and Governance Controls

- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/mocks/module/MockIpRoyaltyVaultV2.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/VaultController.t.sol
- test/foundry/upgrades/Upgrades.t.sol
A restriction is added on the ip royalty vault in which only the grouping module can claim on behalf of group pools to prevent accounting errors in the grouping module / group pools.
> Grouping & Royalty integration refactor

- contracts/interfaces/modules/licensing/ILicenseTemplate.sol
- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/lib/Errors.sol
- contracts/lib/Licensing.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/licensing/PILicenseTemplate.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/mocks/module/MockLicenseTemplate.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces a new configuration item, `commercialRevShare`, in the `LicenseConfig` to allow IP owners to customize and override the royalty percentage defined in the license terms. This enhancement enables derivative IPs to customize or change the royalty percentage for their further children/descendants.
- **New Configuration Item**: Added `commercialRevShare` to the `LicenseConfig`.
- **Override Mechanism**: Implemented logic to override the `commercialRevShare` read from the license terms with the customized value set in the `LicenseConfig`.
- **Customization**: Allow IP owners to set a custom royalty percentage for each license.
- **Override Default**: Enable the custom `commercialRevShare` to override the default value from the license terms when a child IP registers a …
> Allow IP Owner to Customize and Override Royalty Percentage in License Terms

- contracts/interfaces/modules/grouping/IGroupingModule.sol
- contracts/interfaces/registries/IGroupIPAssetRegistry.sol
- contracts/modules/grouping/GroupingModule.sol
- contracts/registries/GroupIPAssetRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR introduces functionality to support unwhitelisting a group reward pool. This allows the protocol to remove a previously whitelisted group reward pool.
> Support Unwhitelisting a Group Reward Pool

- contracts/interfaces/modules/licensing/ILicensingModule.sol
- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/integration/flows/disputes/Disputes.t.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/integration/flows/licensing/LicensingScenarios.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/invariants/DisputeModule.t.sol
- test/foundry/invariants/LicensingModule.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces a `maxMintingFee` parameter for minting license tokens and registering derivatives. This allows the caller to set the maximum minting fee they are willing to pay, providing better control over the costs associated with these operations.
- **Max Minting Fee Parameter**: Added a `maxMintingFee` parameter to the functions for minting license tokens and registering derivatives.
- **Fee Validation**: Implemented logic to validate that the minting fee does not exceed the specified `maxMintingFee`.
- **Cost Control**: Allow callers to set a maximum minting fee they are willing to pay.
- **Fee Validation**: Ensure that the minting fee does not exceed the specified maximum.
1. **Add Max Minting Fee Parameter**: Update the functions for minting license tokens and registering …
> Introduce Max Minting Fee for License Token Minting and Derivative Registration

- script/foundry/utils/DeployHelper.sol
Add `EvenSplitGroupPool` to `ProtocolPauser` in deployment script to allow `EvenSplitGroupPool` to be paused by `ProtocolPauseAdmin`
> Add Missing Pausable Config in Deployment Script

- contracts/modules/royalty/policies/LAP/RoyaltyPolicyLAP.sol
- contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol
This PR makes the `transferToVault` functions in `RoyaltyPolicyLAP` and `RoyaltyPolicyLRP` pausable.
> fix(royalty-policy): make `transferToVault` pausable

- contracts/interfaces/modules/dispute/IDisputeModule.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/DisputeModule.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
This PR adds a cooldown when setting a new arbitration policy.
When a user sets a new arbitration policy the change will only become effective after the cooldown period has passed.
Before the cooldown period has passed the previous royalty policy will still be the one used if anyone were to raise a dispute against an IP Asset during the cooldown period.
> Add set arbitration policy cooldown

- contracts/modules/dispute/DisputeModule.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/invariants/DisputeModule.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/utils/BaseTest.t.sol
Removes the previous tag `PLAGIARISM` and adds the new dispute tags:
- `IMPROPER_REGISTRATION` - party A registered another’s work as its own
- `IMPROPER_USAGE` - violations of commercial rights, territory, channels, etc
- `IMPROPER_PAYMENT` - disputed IP received payments that should have been shared with party A
- `CONTENT_STANDARDS_VIOLATION` - violation of the point in the content standards in the PIL
> Add new dispute tags to deployment script and unit tests

- script/foundry/utils/DeployHelper.sol
This PR updates the deployment script to include Wrapped IP (WIP) as a whitelisted currency token when deploying the protocol. This ensures that WIP is recognized and can be used within the protocol from the moment of deployment.
- **Whitelist WIP**: Added Wrapped IP (WIP) to the list of whitelisted currency tokens in the deployment script.
> Configure Wrapped IP (WIP) as Whitelisted Currency Token

- contracts/interfaces/modules/grouping/IGroupingModule.sol
- contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol
- contracts/interfaces/modules/royalty/policies/IVaultController.sol
- contracts/lib/Errors.sol
- contracts/modules/grouping/GroupingModule.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
- contracts/modules/royalty/policies/VaultController.sol
- package.json
- script/foundry/utils/DeployHelper.sol
- test/foundry/integration/BaseIntegration.t.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/invariants/IpRoyaltyVault.t.sol
- test/foundry/mocks/grouping/MockEvenSplitGroupPool.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/LAP/RoyaltyPolicyLAP.t.sol
- test/foundry/modules/royalty/LRP/RoyaltyPolicyLRP.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/modules/royalty/VaultController.t.sol
- yarn.lock
This PR simplifies the `IpRoyaltyVault` contract by removing the requirement to use snapshots for claiming revenue. The new approach keeps track of the latest pending claimable revenue, allowing users to check the current pending revenue or claim all pending revenue with a single call.
- **Remove Snapshot Functionality**: Eliminated the need for creating and managing snapshots.
- **Simplified Claim Process**: Users can now claim all pending revenue without specifying snapshot IDs.
>  Simplify IpRoyaltyVault to Support Claiming Revenue Without Snapshots

- contracts/lib/Errors.sol
- contracts/registries/IPAssetRegistry.sol
- test/foundry/invariants/IPAssetRegistry.t.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR updates the IP registration process to be idempotent. When attempting to register an IP with the same `chainId`, `nftTokenContract`, and `tokenId`, the function will now return the existing `ipId` instead of reverting. This ensures that the registration process is idempotent.
- **Idempotent Registration**: Modified the IP registration function to return the existing `ipId` if the IP is already registered with the same `chainId`, `nftTokenContract`, and `tokenId`.
- **Ensure Idempotency**: Make the IP registration process idempotent by returning the existing `ipId` for duplicate registrations.
- **Improve User Experience**: Allow users to safely re-register IPs without causing errors or reverts.
1. **Update Registration Function**: Modify the IP registration function to check for …
> Make IP Registration Idempotent by Returning Existing IP ID

- contracts/access/AccessControlled.sol
- contracts/access/AccessController.sol
- contracts/lib/registries/IPAccountChecker.sol
- contracts/modules/dispute/DisputeModule.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/IPAccount.t.sol
- test/foundry/mocks/module/MockMetaTxModule.sol
- test/foundry/mocks/module/MockModule.sol
- test/foundry/mocks/module/MockOrchestratorModule.sol
- test/foundry/registries/IPAccountRegistry.t.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR introduces validation checks to ensure that IP Account addresses are registered through the `IPAssetRegistry`. This enhancement improves the integrity and security of the IP registration process by verifying the legitimacy of IP Account addresses.
- **IP Account Validation**: Added checks to validate that IP Account addresses are registered through the `IPAssetRegistry`.
Closes storyprotocol/trust-protocol-contracts-v1#9
> Validate IP Account Address Registration Through IPAssetRegistry

- contracts/lib/Errors.sol
- contracts/modules/grouping/GroupingModule.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR introduces checks to ensure that IPs with expiration times cannot be added to a group. This enhancement improves the integrity of the grouping process by preventing IPs that have expiration times from being included.
- **Expiration Time Check**: Added logic to verify that IPs being added to a group do not have expiration times.
- **Revert on IPs with Expiration**: The `addIp` function now reverts if any IP in the provided list has an expiration time.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/5
> Prevent Adding IPs with Expiration Time to Group

- contracts/lib/Errors.sol
- contracts/lib/Licensing.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces functionality that allows IP owners to disable a license, preventing the minting of license tokens or the registration of derivatives for the IP through the disabled license. Additionally, IP owners can re-enable a disabled license.
- **License Disabling**: Added functionality for IP owners to disable a license, which prevents minting license tokens and registering derivatives.
- **Control Over Licensing**: Provide IP owners with the ability to control the availability of their licenses.
- **Prevent Unauthorized Use**: Ensure that disabled licenses cannot be used to mint tokens or register derivatives.
This update provides IP owners with greater control over their licenses, enhancing the security and management of IP assets.
Closes #287
> Support for IP Owner to Enable/Disable Licenses

- contracts/modules/licensing/PILicenseTemplate.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR adds a check to ensure that the `licensingConfig` can only increase the royalty percentage compared to the royalty percentage defined in the license terms. This prevents child IPs from overriding parent IPs' royalty percentages with unreasonably low percentages, maintaining fair royalty distribution.
- **Royalty Percentage Check**: Added logic to verify that the new royalty percentage in `licensingConfig` is not lower than the royalty percentage defined in the license terms.
> Enforce Licensing Config to Only Increase Royalty Percentage

- contracts/modules/royalty/RoyaltyModule.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
This PR ensures royalty policy propagation is made only to children IPs. Parents royalty policies remain immutable once the IP is created.
Child IPs receive the royalty policies of their parents plus (if different) the royalty policy on the license being used to link to the parents.
> Ensure royalty policy propagation is made only to children

- contracts/lib/Errors.sol
- contracts/modules/grouping/GroupingModule.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR introduces a check to ensure that Group IPAs must attach non-default license terms before adding IPs into the group. This enhancement ensures that all IPs within a group adhere to specific licensing terms.
- **Non-Default License Terms Check**: Added logic to verify that Group IPAs have non-default license terms attached before allowing IPs to be added to the group.
> Enforce Group IPA to Attach Non-Default License Terms for Adding IPs

- contracts/interfaces/modules/licensing/ILicensingModule.sol
- contracts/interfaces/modules/royalty/IRoyaltyModule.sol
- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/royalty/RoyaltyModule.sol
- test/foundry/integration/BaseIntegration.t.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/integration/flows/disputes/Disputes.t.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/integration/flows/licensing/LicensingScenarios.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/invariants/DisputeModule.t.sol
- test/foundry/invariants/IpRoyaltyVault.t.sol
- test/foundry/invariants/LicensingModule.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/modules/royalty/LAP/RoyaltyPolicyLAP.t.sol
- test/foundry/modules/royalty/LRP/RoyaltyPolicyLRP.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
Adds a new variable `maxRts` defined by the user when registering a derivative to ensure that the royalty tokens distributed to royalty policies does not go over the specified limit.
> Add maxRts restriction when creating a derivative

- contracts/interfaces/modules/grouping/IGroupRewardPool.sol
- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/lib/Errors.sol
- contracts/lib/Licensing.sol
- contracts/modules/grouping/EvenSplitGroupPool.sol
- contracts/modules/grouping/GroupingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/mocks/grouping/MockEvenSplitGroupPool.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces two new license configuration items for groups: `expectMinimumGroupRewardShare` and `expectGroupRewardPool`. These configurations allow individual IPs to define restrictions for being added to a group. 
- `expectMinimumGroupRewardShare`: Specifies the minimum percentage of the group’s reward share that must be allocated to the IP.
- `expectGroupRewardPool`: Specifies that the IP can only be added to a group with a specific reward pool. If set to `address(0)`, the IP cannot be added to any group.
- **New License Configurations**: Added `expectMinimumGroupRewardShare` and `expectGroupRewardPool` to the `LicensingConfig` struct.
- **Validation Logic**: Implemented checks to enforce the new configurations when adding IPs to groups.
- **Restrict Group Addition**: Allow IPs …
> Introduce License Configurations for Group Restrictions

- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/modules/royalty/LRP/RoyaltyPolicyLRP.t.sol
Fixes the LRP royalty policy minting restriction to not include LRP royalty stack given it's not necessary.
> Fix on license minting restriction

- contracts/modules/dispute/DisputeModule.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
When propagating a dispute tag to derivatives - with this change - the dispute created in `tagDerivativeIfParentInfringed` now uses the same arbitration policy as the original dispute that is being propagated.
> Propagate dispute tags with parent arbitration policy

- script/foundry/deployment/Main.s.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/utils/BaseTest.t.sol
This PR updates the protocol deployment script to allow specifying a custom CREATE3 deployer address. 
Example:
create3 deployer is `0x384a891dFDE8180b054f04D66379f16B7a678Ad6` and seed is `9`
```shell
forge script script/foundry/deployment/Main.s.sol:Main  0x384a891dFDE8180b054f04D66379f16B7a678Ad6 9 --sig "run(address,uint256)" --fork-url <rpc> --broadcast --sender <transaction sender wallet address>  --priority-gas-price 1 --legacy 
```
> Allow Specifying CREATE3 Deployer in Protocol Deployment Script

- contracts/interfaces/modules/base/IViewModule.sol
- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/lib/AccessPermission.sol
- contracts/lib/Errors.sol
This pull request addresses several minor typos across multiple files in the project. It includes:
1. **IViewModule.sol**: Corrected a typo in the `namesapces` comment to `namespaces`.
2. **ILicenseRegistry.sol**: Fixed a typo in the return description `count o parent IPs` to `count of parent IPs`.
3. **AccessPermission.sol**: Adjusted phrasing in a comment from `having not enough information` to `not having enough information` for better readability.
4. **Errors.sol**: Corrected multiple typos in comments, including:
- `has no attached any license terms` -> `has not attached any license terms`
- `Licensing hook is invalid either not support` -> `Licensing hook is invalid either does not support`
- `IP is dipute tagged` -> `IP is dispute tagged`
- `module name is already regsitered` -> …
> Fixer mixer

- contracts/lib/AccessPermission.sol
- script/foundry/deployment/Main.s.sol
This PR updates the protocol deployment script to utilize a pre-deployed common CREATE3 deployer at address: `0x9fBB3DF7C40Da2e5A0dE984fFE2CCB7C47cd0ABf`
Also fix a lint error in this PR.
> Use Pre-Deployed Unified CREATE3 Deployer

- contracts/modules/dispute/DisputeModule.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
Adds `updateActiveArbitrationPolicy()` call to `setArbitrationPolicy()` to update the arbitration policy for an IP in case there is an existing queued arbitration policy with cooldown time that has passed.
> Add _updateActiveArbitrationPolicy() is setArbitrationPolicy()

- contracts/interfaces/modules/royalty/policies/IExternalRoyaltyPolicy.sol
- contracts/interfaces/modules/royalty/policies/IExternalRoyaltyPolicyBase.sol
- contracts/interfaces/modules/royalty/policies/IRoyaltyPolicy.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/RoyaltyModule.sol
- test/foundry/mocks/policy/MockExternalRoyaltyPolicy1.sol
- test/foundry/mocks/policy/MockExternalRoyaltyPolicy2.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
Adds ERC165 for external royalty policy registration to check if it implements the function `getPolicyRtsRequiredToLink` - check is made via the function selector.
> Adds ERC165 check for external royalty policy registration

- contracts/lib/Errors.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces a check to prevent derivative IPs from being linked to the same parent IPs when registering derivatives. It ensures that there are no duplicate parent IPs passed in when registering a derivative with multiple parents.
- **Duplicate Parent IP Check**: Added logic to verify that there are no duplicate parent IPs when registering a derivative IP.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/14
> Prevent Duplicate Parent IPs When Registering Derivative IP

- contracts/interfaces/modules/royalty/policies/IGraphAwareRoyaltyPolicy.sol
- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/LAP/RoyaltyPolicyLAP.sol
- contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/mocks/policy/MockRoyaltyPolicyLAP.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/royalty/LAP/RoyaltyPolicyLAP.t.sol
- test/foundry/modules/royalty/LRP/RoyaltyPolicyLRP.t.sol
Removes the `amount` input from the `transferToVault()` function.
> Remove amount input from transferToVault() function

- contracts/modules/dispute/policies/UMA/ArbitrationPolicyUMA.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/modules/royalty/policies/LAP/RoyaltyPolicyLAP.sol
- contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol
Fix to ensure that when used - the nonReentrant modifier - is the first modifier as it's the best practice.
> Fix nonReentrant modifier order

- GUIDELINES.md
- test/foundry/modules/licensing/README.md
This PR includes comprehensive updates to both Engineering Guidelines and Licensing documentation.
-  GUIDELINES.md
- .test/foundry/modules/licensing/README.md
Fixed typos and grammar:
- ✅ "Test should use" → "Tests should use"
- ✅ "upgreadeability" → "upgradeability"
- ✅ "methods an events" → "methods and events"
- ✅ "worklows" → "workflows"
> Add Security Testing Requirements and Update Documentation

- test/hardhat/e2e/license/attachLicenseTerms.test.ts
- test/hardhat/e2e/license/mintLicenseTokens.test.ts
- test/hardhat/e2e/license/registerDerivative.test.ts
- test/hardhat/e2e/license/registerLicenseTerms.test.ts
- test/hardhat/e2e/permission/permission.test.ts
- test/hardhat/e2e/setup.ts
- test/hardhat/e2e/utils/erc20Helper.ts
This pr adds tests for PILicenseTemplate and Licensing Module, includes：
- PILicenseTemplate
- Register non-commercial PIL license terms
- Register commercial use license terms
- Register commercial remix license terms
- Register commercial remix license terms with commercialRevShare larger than max value
- Licensing Module
- IP Asset attach a license except for default one
- IP asset owner mint license tokens
- Non-IP asset owner mint license tokens
- Mint license tokens with amount 0
- Mint license tokens with different receivers
- Register derivative with the license that parent IP attached
- Register derivative with the license that parent IP doesn’t attached
- IP asset already attached a non-default license and register derivative
- License token holder register derivative with the …
> Add tests for PILicenseTemplate and Licensing Module

- contracts/registries/GroupIPAssetRegistry.sol
This PR updates the `getGroupMembers` function to initialize the results array dynamically based on the size of the group members. This change ensures that the results array is correctly sized to hold the group members being retrieved.
Closes https://github.com/storyprotocol/halborn-protocol-contracts-v1/issues/5
> Initialize Dynamic Results Array for Group Members

- contracts/modules/grouping/EvenSplitGroupPool.sol
This PR updates the `EvenSplitGroupPool` contract to use SafeERC20's `forceApprove()` method to ensure the approval allowance of the reward token to the `RoyaltyModule`. This change ensures compatibility with all ERC20 tokens, including those with non-standard implementations such as USDT.
- **SafeERC20 `forceApprove()`**: Updated the `distributeRewards` function to use SafeERC20's `forceApprove()` method for setting the allowance of the reward token to the `RoyaltyModule`.
Closes https://github.com/storyprotocol/halborn-protocol-contracts-v1/issues/9
> Apply SafeERC20's `forceApprove()` for Reward Token Allowance to RoyaltyModule

- contracts/interfaces/modules/dispute/IDisputeModule.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/DisputeModule.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
- test/foundry/utils/BaseTest.t.sol
As a simplification and to avoid possible edge cases, each arbitration policy will only have only 1 relayer address.
> Change to only 1 relayer address per arbitration policy

- contracts/LicenseToken.sol
- contracts/interfaces/ILicenseToken.sol
- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/LicenseToken.t.sol
This PR updates the `LicenseToken` contract to store the commercial revenue share (royalty percentage) in the license token metadata. It also ensures that this stored percentage is used when registering derivatives with the license token, preventing the parent IP owner from updating the royalty percentage after minting the license token.
- **Store Commercial Revenue Share**: Updated the `LicenseToken` contract to store the commercial revenue share in the license token metadata.
- **Use Stored Percentage for Derivative Registration**: Modified the derivative registration process to use the stored commercial revenue share from the license token.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/13
> Store Commercial Revenue Share in License Token and Use it for Derivative Registration

- contracts/access/IPGraphACL.sol
- contracts/interfaces/access/IIPGraphACL.sol
- test/foundry/access/IPGraphACL.t.sol
This PR updates the `IPGraphACL` contract to emit events when an address is whitelisted or revoked. 
- **Emit Whitelist Event**: Added an event emission when an address is whitelisted.
- **Emit Revoke Event**: Added an event emission when an address is revoked from the whitelist.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/42
> Emit Events for Whitelist and Revoke Address in IPGraphACL

- contracts/modules/grouping/GroupingModule.sol
This PR updates the `GroupingModule` contract to apply the `nonReentrant` modifier to the `collectRoyalties()`, `claimReward()`, `addIp()`, and `removeIp()` functions. This change is made to prevent reentrancy attacks and ensure the security of these critical functions.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/41
> Apply `nonReentrant` Modifier to Critical Functions in `GroupingModule`

- contracts/modules/licensing/LicensingModule.sol
This PR removes the unused `childIpOwner` parameter from internal functions in the `LicensingModule` contract, such as `_executeLicensingHookAndPayMintingFee`. 
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/39
> Remove Unused `childIpOwner` Parameter from Internal Functions in `LicensingModule`

- contracts/lib/Errors.sol
- contracts/modules/grouping/GroupingModule.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR updates the `GroupingModule` contract to check and prevent to add IPs that have been tagged with disputes to Group IPA. This change ensures that disputed IPs cannot be added to groups.
- **Dispute Check**: Added a check in the `addIp` function to prevent the addition of IPs that have been tagged with disputes.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/23
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/22
> Prevent Adding Dispute-Tagged IPs to Groups in `GroupingModule`

- contracts/LicenseToken.sol
- contracts/lib/Errors.sol
- test/foundry/LicenseToken.t.sol
This PR updates the `LicenseToken` contract to check and prevent the setting of a commercial revenue share (royalty percentage) over 100% (100,000,000) when minting license tokens. This change ensures that the royalty percentage remains within a valid range, maintaining the integrity of the licensing process.
- **Royalty Percentage Check**: Added a check in the `LicenseToken` contract to prevent setting a commercial revenue share over 100% when minting license tokens.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/4
> Prevent Royalty Commercial Revenue Share Over 100% When Minting License Tokens

- contracts/GroupNFT.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/royalty/IpRoyaltyVault.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
This PR updates the `GroupNFT` contract to use `_safeMint()` instead of `_mint()` when minting Group NFTs. This change ensures that the receiver can handle the NFT properly by checking if the receiver is a contract and if it implements the `IERC721Receiver` interface.
- **Minting Method Update**: Replaced `_mint()` with `_safeMint()` in the `GroupingModule` contract for minting Group NFTs.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/3
> Change from `_mint()` to `_safeMint()` for Minting Group NFTs

- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR introduces a verification step to ensure that all royalty policies are identical when registering a derivative with multiple parent IPs. This change is necessary to maintain consistency and integrity in the licensing process.
- **Royalty Policy Verification**: Added a check to verify that all royalty policies are identical when registering a derivative with multiple parent IPs.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/12
> Implement Verification for Identical Royalty Policies When Registering Derivative with Multiple Parent IPs

- contracts/LicenseToken.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR updates the `LicenseToken` contract to use `_safeMint()` instead of `_mint()` when minting License Tokens. This change ensures that the receiver can handle the NFT properly by checking if the receiver is a contract and if it implements the `IERC721Receiver` interface.
- **Minting Method Update**: Replaced `_mint()` with `_safeMint()` in the `LicenseToken` contract for minting License Tokens.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/2
> Change from _mint() to _safeMint() for Minting License Tokens

- contracts/registries/LicenseRegistry.sol
This PR adds note comments to the `LicenseRegistry` contract to remind developers to perform necessary validations before calling the IP Graph to add a parent IP. Since the precompiled IP Graph does not validate the parent-child relationship, the `LicensingModule` related contracts should handle these validations to ensure data integrity.
- **Note Comments**: Added comments to remind developers to validate the parent-child relationship before calling the IP Graph.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/6
> Add Note Comments for Validations Before Calling IP Graph to Add Parent IP 

- contracts/lib/Errors.sol
- contracts/modules/grouping/GroupingModule.sol
- contracts/modules/royalty/RoyaltyModule.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR introduces a verification step to ensure that the group reward pool is whitelisted before any interaction. This change is necessary to maintain the security and integrity of the reward distribution process.
- **Group Reward Pool Whitelist Check**: Added a check to verify that the group reward pool is whitelisted before interacting with it.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/27
> Check Group Reward Pool is Whitelisted Before Interacting

- contracts/lib/Errors.sol
- contracts/registries/LicenseRegistry.sol
- script/foundry/utils/DeployHelper.sol
- test/foundry/mocks/module/LicenseRegistryHarness.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/utils/BaseTest.t.sol
This PR introduces restrictions to ensure that an empty group cannot have derivative IPs or mint license tokens. Additionally, it prevents a group IP from having any parent IPs. These changes are necessary to maintain the integrity and consistency of the IP management process.
- **Empty Group Restrictions**: Added checks to prevent empty groups from having derivative IPs or minting license tokens.
- **Group IP Parent Restriction**: Added a check to prevent group IPs from having any parent IPs.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/26
> Restrict Group from Having Derivative or Having Parents, or Minting License Tokens

- contracts/modules/grouping/EvenSplitGroupPool.sol
This PR updates the `EvenSplitGroupPool` contract's `distributeRewards` function to reset the allowance to 0 at the end of the function. This change ensures that the contract does not retain any unnecessary allowances, enhancing security and preventing potential misuse.
- **Allowance Reset**: Added code to reset the allowance to 0 at the end of the `distributeRewards` function in the `EvenSplitGroupPool` contract.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/10
> Reset Reward Token Allowance to 0  to RoyaltyModule

- contracts/lib/Errors.sol
- contracts/modules/royalty/policies/IpRoyaltyVault.sol
Fix unsafe casting to uint256.
> Fix unsafe casting to uint256

- contracts/modules/royalty/policies/IpRoyaltyVault.sol
Rename outdated NatSpec `revenueAccBalances` parameter to `vaultAccBalances`.
> NatSpec fix in IpRoyaltyVault.sol

- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR introduces additional validations to the Group IPA to ensure consistency and integrity in the licensing process. The changes include restrictions on attaching license terms, requirements for adding IPs to a group, and freezing certain license configuration items once the group has its first member.
- **Single License Term Validation**: Ensures that a Group IPA can only attach one license term, which must be common to all members.
- **Consistent License Config Validation**: When adding an IP to a Group, the Group and IP must have the same `mintingFee` and `licenseHook` in the `LicenseConfig`. Additionally, the Group's commercial revenue share must be greater than or equal to the IP's commercial revenue share.
- **Freezing License Config Items**: Once a Group has its first member, …
> Add More Validations to Group IPA

- contracts/registries/IPAssetRegistry.sol
- test/foundry/registries/IPAssetRegistry.t.sol
This PR updates the IP registration process to prevent re-charging the registration fee when the same IP is registered idempotently. This change ensures that users are not charged multiple times for registering the same IP, enhancing the user experience and preventing unnecessary costs.
This PR was originally initiated by @maxisch in [PR #1](https://github.com/kingster-will/protocol-core-v1-dev/pull/1).
- **Idempotent Registration**: Added logic to check if an IP is already registered and prevent re-charging the registration fee if it is.
> Prevent Re-Charge of IP Registration Fee for Idempotent Registration

- contracts/IPAccountImpl.sol
- test/foundry/IPAccountMetaTx.t.sol
This PR implements EIP-1271 for the IP Account, adding support for contract-based signature validation. It also integrates access control mechanisms to ensure that only authorized signers can be considered is valid signature.
- **EIP-1271 Implementation**: Added support for EIP-1271 to validate signatures from smart contract.
This update enhances the security of the IP Account by ensuring that only authorized signers can execute transactions and supports contract-based signature validation as per EIP-1271.
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/10
> Implement EIP-1271 with Access Control for IP Account

- contracts/LicenseToken.sol
- contracts/interfaces/ILicenseToken.sol
- contracts/interfaces/modules/licensing/ILicensingModule.sol
- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/LicenseToken.t.sol
- test/foundry/integration/big-bang/SingleNftCollection.t.sol
- test/foundry/integration/flows/disputes/Disputes.t.sol
- test/foundry/integration/flows/grouping/Grouping.t.sol
- test/foundry/integration/flows/licensing/LicensingIntegration.t.sol
- test/foundry/integration/flows/licensing/LicensingScenarios.t.sol
- test/foundry/integration/flows/royalty/Royalty.t.sol
- test/foundry/invariants/DisputeModule.t.sol
- test/foundry/invariants/LicenseToken.t.sol
- test/foundry/invariants/LicensingModule.t.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/modules/licensing/PILicenseTemplate.t.sol
- test/foundry/modules/royalty/RoyaltyModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR introduces a new feature that allows users to specify the maximum royalty percentage (`maxRevenueShare`) they are willing to accept when minting license tokens from an IP or registering a derivative to parent IPs. This change enhances the flexibility and control users have over their licensing agreements.
- **`maxRevenueShare` Parameter**: Added a `maxRevenueShare` parameter to the functions for minting license tokens and registering derivatives.
- **Validation Logic**: Implemented validation logic to ensure that the specified `maxRevenueShare` is not exceeded during the minting or registration process.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/17
> Introduce `maxRevenueShare` for Minting License Tokens and Registering Derivatives

- package.json
- script/foundry/deployment/Main.s.sol
- script/foundry/utils/BroadcastManager.s.sol
- script/foundry/utils/Create3Deployer.sol
- script/foundry/utils/DeployHelper.sol
- script/foundry/utils/ICreate3Deployer.sol
- script/foundry/utils/upgrades/DeployerUtils.sol
- script/foundry/utils/upgrades/UpgradeExecutor.s.sol
- test/foundry/utils/BaseTest.t.sol
- test/foundry/utils/TestProxyHelper.sol
- yarn.lock
This PR includes the deployment of the protocol using the pre-deployed CREATE3 deployer. The changes ensure that the protocol contracts are deployed efficiently and consistently using the CREATE3 deployment method.
- **Deployment Script Update**: Modified the deployment script to utilize the pre-deployed CREATE3 deployer for deploying protocol contracts.
- **Contract Deployment**: Deployed all necessary protocol contracts using the CREATE3 deployer.
> Deploy Protocol Using Pre-Deployed CREATE3 Deployer

- contracts/LicenseToken.sol
- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR ensures that an IP cannot be registered as a derivative of any IP once the IP owner has minted a private license token of a non-default license. This change enhances the integrity of the licensing system by preventing unauthorized derivative registrations.
- **Derivative Registration Restriction**: Added logic to prevent an IP from being registered as a derivative if a private license token of a non-default license has been minted by the IP owner.
> Ensure IP Cannot Be Registered as Derivative After Minting Private License Token

- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
- test/foundry/registries/LicenseRegistry.t.sol
This PR removes the ability to set licensing configurations at the IP level, requiring all configurations to be set at the specific license template and terms ID level. 
- Modified `setLicensingConfig()` to require both licenseTemplate and licenseTermsId parameters
- Removed IP-level configuration fallback logic
- Updated error handling to enforce non-zero license template addresses
- Added validation to ensure licenseTermsId is non-zero when setting config
- Removed storage and logic for IP-level configurations
- Updated `getLicensingConfig()` to only return license-specific configurations
- Modified event emissions to reflect removal of IP-level configs
- Updated test cases to remove IP-level configuration scenarios
- Added new test cases to verify proper validation of license template …
> Remove IP-Level Licensing Configuration

- contracts/access/AccessController.sol
- contracts/interfaces/access/IAccessController.sol
- test/foundry/access/AccessController.t.sol
This PR introduces transient permissions in the Access Controller, allowing users to set one-time use permissions that only take effect in the current transaction. This feature enhances the flexibility and security of the permission management system.
- **Transient Permission Implementation**: Added functionality to set and check transient permissions that are valid only for the current transaction.
> Introduce Transient Permission in Access Controller

- contracts/modules/dispute/policies/UMA/ArbitrationPolicyUMA.sol
Adjusts the UMA claim to penalize duplicate disputes. Raising a duplicate dispute can now be countered with just the fact that a similar dispute has already been raised against the IP in the past.
> Adjust claim

- contracts/lib/Errors.sol
- contracts/modules/grouping/EvenSplitGroupPool.sol
- contracts/registries/GroupIPAssetRegistry.sol
Description
This PR enforces a maximum size limit of 1000 members for each group in the `GroupIPAssetRegistry`. This change ensures that no group can exceed the specified limit.
> Enforce Group Max Size Limit of 1000

- contracts/lib/Errors.sol
- contracts/modules/licensing/LicensingModule.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR introduces validation to ensure that licensing hooks cannot set minting fees lower than what is specified in the license terms. This prevents potential fee circumvention.
- Add new error `LicensingModule__LicensingHookMintingFeeBelowLicenseTerms` to handle cases where licensing hook sets a minting fee lower than license terms
- Add validation in LicensingModule to check if licensing hook's minting fee is less than the license terms' minting fee
- Update test cases with lower minting fees (from 999/300 to 100)
- Add new test cases to verify the minting fee validation:
- test_LicensingModule_mintLicenseTokens_revert_LicensingHookMintingFeeBelowLicenseTerms
- test_LicensingModule_registerDerivative_revert_LicensingHookMintingFeeBelowLicenseTerms
- …
> Add validation for licensing hook minting fees

- contracts/interfaces/registries/ILicenseRegistry.sol
- contracts/modules/licensing/LicensingModule.sol
- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR ensures that the license template of a private license token always matches the license template of the attached license terms. This change enforces consistency and prevents discrepancies between the license templates.
- **License Template Validation**: Added validation to ensure the license template of a private license token matches the license template of the attached license terms.
> Ensure Private License Token's License Template Matches Attached License Terms

- contracts/access/AccessController.sol
- contracts/lib/Errors.sol
- test/foundry/access/AccessController.t.sol
This PR introduces a restriction in the `AccessController` to disallow setting permissions for nested IP Accounts which owned by another IP Account. 
- **Permission Restriction**: Added logic to prevent setting permissions for nested IP Accounts in the `AccessController`.
> Disallow Setting Permissions for Nested IP Accounts in AccessController

- contracts/registries/LicenseRegistry.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR fixes a security vulnerability that allowed Group IPs to bypass licensing restrictions by minting license tokens using terms that weren't officially attached to the group (i.e. private license tokens).
To fix this issue, this PR modified `verifyMintLicenseToken()` in the in the `LicenseRegistry` to ensure group IPs can only mint license tokens for terms that are attached to the group.
Added a test case `test_GroupingModule_mintLicenseToken_revert_groupIpHasNoLicenseTerms()` that verifies:
- A group IP cannot mint license tokens for terms that aren't attached to it
- The system properly reverts with the expected error message when this is attempted
> Restrict Group IPs to Only Mint Tokens for Attached License Terms

- contracts/modules/licensing/PILicenseTemplate.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR adds a security fix that prevents license terms with `derivativesApproval = true` from being attached to group IP assets. This change addresses a vulnerability where the derivative approval requirement could be bypassed through group IPs.
When a license has `derivativesApproval = true`, it requires the IP owner's explicit approval for derivatives. However, when such IPs are added to a group, this restriction could be bypassed:
- Create a group IP containing the restricted IP
- Approve deriving from the group IP (the group could be owned by a malicious user)
- Create a derivative of the group IP
This effectively circumvents the IP owner's intention to approve derivatives.
Added a check in `PILicenseTemplate.canAttachToGroupIp()` that returns `false` when license terms have …
> Prevent License Terms with Derivative Approval from Attaching to Group IPs

- contracts/modules/licensing/LicensingModule.sol
- test/foundry/modules/licensing/LicensingModule.t.sol
This PR adds the `verifyPermission(ipId)` modifier to the `attachDefaultLicenseTerms` function in the LicensingModule contract.
- Add `verifyPermission(ipId)` modifier to the `attachDefaultLicenseTerms` function
- Add test cases to verify proper permission enforcement
All other functions that modify IP asset properties in the LicensingModule (such as `attachLicenseTerms`, `registerDerivative`, etc.) already use the `verifyPermission` modifier to ensure that only the IP owner or authorized users can make changes. This function was missing this check.
Added two test cases:
1. `test_LicensingModule_attachDefaultLicenseTerms_revert_NoPermission` - Verifies that unauthorized users cannot attach default license terms
2. `test_LicensingModule_attachDefaultLicenseTerms_withPermission` - Verifies …
> Add permission verification to `attachDefaultLicenseTerms` function

- test/hardhat/e2e/grouping/group.ipa.test.ts
- test/hardhat/e2e/utils/licenseHelper.ts
New tests:
- 1. Should revert when mint license tokens for terms that aren't attached to a group IP 
- 2. Should revert when attach a license with derivativesApproval = true to a group IP and should succeed when attach a license with derivativesApproval = false to a group IP
https://github.com/storyprotocol/protocol-core-v1/pull/413
https://github.com/storyprotocol/protocol-core-v1/pull/412
> Add new grouping tests

- test/hardhat/e2e/ipaccount/ipaccount.test.ts
- test/hardhat/e2e/royalty/royalty.test.ts
This pr adds e2e tests for poc changes, includes:
- Test the transfer of royalties to the same IP account's vault
- Test the state update of IPAccount on Asset Changes
> add tests for 1.3.2 change

- test/hardhat/e2e/ipaccount/ipaccount.test.ts
add test for #408 (Removed support for ERC 1271 signatures in the IPAccount contract)
Tests passed on local MAC.
```sh
✓ Test passed: Contract properly handles empty signature
✔ should handle empty signature (346ms)
4 passing (3m)
```
> test: add ERC1271 signature validation tests for IPAccount

- contracts/interfaces/modules/dispute/IDisputeModule.sol
- contracts/interfaces/modules/dispute/policies/IArbitrationPolicy.sol
- contracts/interfaces/modules/dispute/policies/UMA/IArbitrationPolicyUMA.sol
- contracts/lib/Errors.sol
- contracts/modules/dispute/DisputeModule.sol
- contracts/modules/dispute/policies/UMA/ArbitrationPolicyUMA.sol
- test/foundry/mocks/dispute/MockArbitrationPolicy.sol
- test/foundry/modules/dispute/DisputeModule.t.sol
- test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
To improve UX for wrapper contracts integrating with the dispute module a new function `raiseDisputeOnBehalf` is created which allows passing an arbitrary dispute initiator.
> Add new function raiseDisputeOnBehalf

- GUIDELINES.md
This PR fixes a broken link to the Foundry docs, as /tutorials is now /guides in the Foundry docs
> fix: broken link

- contracts/modules/grouping/GroupingModule.sol
- test/foundry/modules/grouping/GroupingModule.t.sol
This PR enhances the `GroupingModule` by automatically deploying royalty vaults for group members during the `claimReward` process if they do not already exist.
Previously, vaults for all member IPs in a group needed to be manually deployed before rewards could be claimed. This change simplifies the workflow by handling the vault deployment on-the-fly within the `claimReward` function.
- **`contracts/modules/grouping/GroupingModule.sol`**:
- The `claimReward` function now iterates through the provided `ipIds`.
- For each `ipId`, it checks if a royalty vault exists.
- If a vault is not found (`ROYALTY_MODULE.ipRoyaltyVaults(ipIds[i]) == address(0)`), it automatically calls `ROYALTY_MODULE.deployVault(ipIds[i])` to create it before distributing rewards.
- …
> feat(grouping): automatic royalty vault deployment during reward claim

- test/foundry/invariants/IPAssetRegistry.t.sol
This PR addresses a issue in the `IPAssetRegistryHarness` where the `registered` counter was incorrectly incremented for already registered IP accounts. This led to inaccurate accounting and failures in invariant tests.
The fix makes sure that the `registered` counter is only incremented if an IP account transitions from an unregistered to a registered state within the `harness.register()` function. This is achieved by checking the registration status before and after the `ipAssetRegistry.register()` call.
Test results are attached: [test_result.txt](https://github.com/user-attachments/files/20513238/test_result.txt)
> fix(test): ensure accurate tracking of registered IP accounts in test harness

- contracts/lib/PILFlavors.sol
This PR fixes a typo in the documentation of the `commercialUse` function of the PILFlavors contract 
Gets the values to create a Non Commercial Social Remix licenseTerms flavor -> Gets the values to create a Commercial Use licenseTerms flavor
> PILFlavors documentation fix

- test/foundry/modules/dispute/DisputeModule.t.sol
This PR adds new test cases to the DisputeModule.t.sol test suite, targeting the raiseDispute and raiseDisputeOnBehalf functions. The new tests ensure that the contract correctly reverts when an invalid dispute initiator attempts to raise a dispute.
Added `test_DisputeModule_raiseDispute_revert_InvalidDisputeInitiator` to verify that only valid initiators can call raiseDispute.
Added `test_DisputeModule_raiseDisputeOnBehalf_revert_InvalidDisputeInitiator` to verify that only valid initiators can call raiseDisputeOnBehalf.
Both tests check for the correct revert reason (DisputeModule__InvalidDisputeInitiator).
> Add test cases to dispute module RaiseDispute and RaiseDisputeOnBehalf
