README.md
Instructions on how to use the script to generate boilerplate code and the namespaced storage layout hash.
=> Added ERC7201 explainer to README

contracts/IPAccountImpl.sol, contracts/access/AccessControlled.sol, contracts/access/AccessController.sol, contracts/interfaces/access/IAccessController.sol, script/foundry/deployment/Main.s.sol, test/foundry/access/AccessController.t.sol, test/foundry/mocks/access/MockAccessController.sol, test/foundry/mocks/module/MockMetaTxModule.sol, test/foundry/modules/licensing/PILPolicyFramework.derivation.t.sol, test/foundry/modules/licensing/PILPolicyFramework.multi-parent.sol, test/foundry/modules/licensing/PILPolicyFramework.t.sol, test/foundry/utils/BaseTest.t.sol, test/foundry/utils/DeployHelper.t.sol, test/foundry/utils/LicensingHelper.t.sol
Move AccessController.sol and IAccessController.sol into `access` folder
=> Refactor Access Controller into access folder

contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol, contracts/modules/royalty/policies/IpRoyaltyVault.sol, test/foundry/modules/royalty/IpRoyaltyVault.t.sol
Adds claim event to IpRoyaltyVault.sol
=> add claim event

Makefile, foundry.toml, remappings.txt, slither.config.json
- Update Makefile
- Clean remappings
- Use env var in foundry.toml
=> Clean minor configs

contracts/lib/PILFlavors.sol, contracts/modules/licensing/PILicenseTemplate.sol, script/foundry/utils/DeployHelper.sol, test/foundry/integration/flows/licensing/LicensingIntegration.t.sol, test/foundry/modules/licensing/PILicenseTemplate.t.sol
Make PILicenseTemplate UUPS upgradeable.
Closes #81
=> UUPS upgradeable for PILicenseTemplate

contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol, contracts/interfaces/modules/royalty/policies/IRoyaltyPolicyLAP.sol, contracts/modules/royalty/policies/IpRoyaltyVault.sol, contracts/modules/royalty/policies/RoyaltyPolicyLAP.sol
Emit when actually adding a new token to a vault
=> Ignored return value

test/foundry/access/btt/AccessControlled.tree, test/foundry/access/btt/AccessController.checkPermission.tree, test/foundry/access/btt/AccessController.setPermission.tree, test/foundry/modules/dispute/btt/ArbitrationPolicySP.tree, test/foundry/modules/dispute/btt/DisputeModule.actions.tree, test/foundry/modules/dispute/btt/DisputeModule.setters.tree, test/foundry/modules/external/btt/TokenWithdrawalModule.tree, test/foundry/modules/metadata/btt/CoreMetadataModule.tree, test/foundry/modules/metadata/btt/CoreMetadataViewModule.tree, test/foundry/modules/royalty/btt/IpRoyaltyVault.claim.tree, test/foundry/modules/royalty/btt/IpRoyaltyVault.setters.tree, test/foundry/modules/royalty/btt/IpRoyaltyVault.snapshot.tree, test/foundry/modules/royalty/btt/RoyaltyModule.callbacks.tree, test/foundry/modules/royalty/btt/RoyaltyModule.payment.tree, test/foundry/modules/royalty/btt/RoyaltyModule.setters.tree, test/foundry/modules/royalty/btt/RoyaltyPolicyLAP.tree, test/foundry/registries/btt/IPAccountRegistry.tree, test/foundry/registries/btt/IPAssetRegistry.tree, test/foundry/registries/btt/LicenseRegistry.attachLicenseTermsToIp.tree, test/foundry/registries/btt/LicenseRegistry.registerDerivativeIp.tree, test/foundry/registries/btt/LicenseRegistry.setters.tree, test/foundry/registries/btt/ModuleRegistry.tree
Using [Branching Tree Technique](https://github.com/PaulRBerg/btt-examples) for structured unit testing.
**Access Controller**
**Royalty**
**Dispute**
**Registries**
**Modules**
Structured tests around BTT above
**IPAccount**
- IPAccount
**Licensing**
- LicensingModule
- LicenseToken
- PILicenseTemplate
Also, need to revisit getters.
=> Add Test Trees for structured BTT-style tests

contracts/modules/royalty/RoyaltyModule.sol
This PR deletes duplicate import of the BaseModule.sol from contracts/modules/royalty/RoyaltyModule.sol
=> delete duplicate import of BaseModule

contracts/modules/dispute/policies/ArbitrationPolicySP.sol
Adds note/comment on ArbitrationPolicySP.sol empty functions
=> Fix empty functions comments

contracts/modules/dispute/DisputeModule.sol, contracts/modules/royalty/policies/IpRoyaltyVault.sol
Adds `nonReentrant` modifier to `resolveDispute` and `claimRevenueBySnapshotBatch`
=> Add nonReentrant fix

test/foundry/mocks/MockIPGraph.sol
Update Mock IPGraph to simulate precompile contract handling Royalty LRP Policy.
=> Update Mock IPGraph to support Royalty LRP Policy

contracts/modules/royalty/RoyaltyModule.sol
Move the new added storage to the end of the struct for support upgradeable properly.
=> Fix royalty module storage layout for upgradeable

UPGRADES.md, contracts/IPAccountImpl.sol, contracts/IPAccountStorage.sol, foundry.toml, script/foundry/deployment/Main.s.sol, script/foundry/deployment/MockAssets.s.sol, script/foundry/utils/DeployHelper.sol, script/foundry/utils/JsonBatchTxHelper.s.sol, script/foundry/utils/JsonDeploymentHandler.s.sol, script/foundry/utils/upgrades/UpgradeExecutor.s.sol, script/foundry/utils/upgrades/UpgradedImplHelper.sol
This PR introduces scripts and instructions to prepare smart contract upgrades and interact with `AccessManager` to perform them.
It also includes some missing annotations for OZ upgrades compat.
Most relevant files:
- `UPGRADES.md` instructions 
- `JsonDeploymentHandler.s.sol` adds methods to read deployment files and write upgrade proposal files
-  `JsonBatchTxHelper.s.sol` helps write raw data for the upgrade actions, that can be used to operate multisigs
- `UpgradeExecutor.s.sol` script that reads upgrade proposal files and schedules, executes or cancels upgrades in `AccessManager`. It supports different modes of execution:
- Each upgrade in a separate transaction
- Batched execution using `AccessManager` multicall
- Don't execute but prepare a JSON file that could be ingested by …
=> Contract upgrade scripts

contracts/modules/licensing/PILicenseTemplate.sol, test/foundry/integration/flows/royalty/Royalty.t.sol
This PR introduces a fix to allow external royalty policy to register terms.
=> PIL license template fix to allow external royalty policy to register terms

script/foundry/deployment/Main.s.sol, script/foundry/utils/DeployHelper.sol, test/foundry/utils/BaseTest.t.sol
Fix the empty version number in file name of deployment output.
=> Fix empty version in deploy output file name.

contracts/interfaces/modules/royalty/IRoyaltyModule.sol, contracts/modules/royalty/RoyaltyModule.sol
Adds the event `IpRoyaltyVaultDeployed`.
=> Add event on royalty vault deployment

contracts/GroupNFT.sol
Remove absolute path in the imports of GroupNFT
=> Fix absolute path in imports of GroupNFT

script/foundry/utils/BroadcastManager.s.sol
Addin devnet networks support to protocol deployment script
=> Add Devnet Network Support to Deployment

contracts/interfaces/modules/royalty/IRoyaltyModule.sol, contracts/modules/royalty/RoyaltyModule.sol, test/foundry/integration/flows/royalty/Royalty.t.sol, test/foundry/modules/royalty/RoyaltyModule.t.sol
Adds amount after fee to royalty related events.
=> Add amount after fee to royalty events

contracts/modules/royalty/RoyaltyModule.sol, contracts/modules/royalty/policies/LAP/RoyaltyPolicyLAP.sol, contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol, contracts/registries/LicenseRegistry.sol, script/foundry/utils/DeployHelper.sol, test/foundry/utils/BaseTest.t.sol
Update Precompiled address to 0x0101 according to latest precompiled IP Graph address.
=> Update precompiled IPGraph Addresses

contracts/modules/grouping/GroupingModule.sol, script/foundry/utils/DeployHelper.sol, test/foundry/integration/flows/grouping/Grouping.t.sol, test/foundry/modules/grouping/EvenSplitGroupPool.t.sol, test/foundry/modules/grouping/GroupingModule.t.sol, test/foundry/modules/royalty/RoyaltyModule.t.sol
This PR updates the deployment script to deploy the native `EvenSplitGroupPool` and modifies the tests accordingly to ensure proper integration and functionality.
- **Deployment Script**: Updated to deploy the native `EvenSplitGroupPool`.
- **Test Updates**: Modified existing tests to accommodate the deployment and integration of the `EvenSplitGroupPool`.
=> Update Deployment Script to Deploy Native EvenSplitGroupPool

script/foundry/utils/BroadcastManager.s.sol
Add support of deploying Protocol on Odyssey Testnet: 1516
=> Support deploy protocol on Odyssey Testnet

script/foundry/utils/DeployHelper.sol
Add missing UPGRADE_ROLE to contracts so that allow to be upgraded.
=> Add missing Function Target Roles For Upgrade in Deployment Script

contracts/modules/grouping/EvenSplitGroupPool.sol, test/foundry/modules/grouping/EvenSplitGroupPool.t.sol
This PR addresses issue #288 by preventing repeated reward claims when `GroupingModule.claimReward()` is called with an array of IP IDs that contains duplicates. The update ensures that each IP ID can only claim rewards once per call, avoiding any potential double-claiming of rewards.
- **Duplicate IP ID Check**: Added logic to track for and handle duplicate IP IDs in the `claimReward()` function.
- **Single Claim Enforcement**: Ensured that each IP ID can only claim rewards once per call.
This update ensures that rewards are claimed correctly and securely, even when duplicate IP IDs are provided.
Closes #288
=> Prevent Repeated Reward Claims From Group Pool for Duplicate IPs

contracts/registries/GroupIPAssetRegistry.sol, test/foundry/modules/grouping/GroupingModule.t.sol
Add a test to cover test scenario that someone try to front-running register an group IP.
Closes #289
=> Add Test of Front-running group registrations

contracts/interfaces/registries/IGroupIPAssetRegistry.sol, contracts/modules/grouping/GroupingModule.sol, contracts/registries/GroupIPAssetRegistry.sol, contracts/registries/IPAssetRegistry.sol, test/foundry/modules/grouping/GroupingModule.t.sol
This PR allows the registration of Group IPAs when the protocol registration fee is enabled and configured. This enhancement ensures that the Group registration process includes the necessary fee payment.
- **Registration Fee Handling**: Added logic to handle the protocol registration fee during the Group IPA registration process.
Closes https://github.com/storyprotocol/trust-protocol-contracts-v1/issues/3
=> Enable Group IPA Registration with Protocol Registration Fee

contracts/lib/Errors.sol, contracts/modules/royalty/RoyaltyModule.sol, test/foundry/modules/royalty/LAP/RoyaltyPolicyLAP.t.sol, test/foundry/modules/royalty/LRP/RoyaltyPolicyLRP.t.sol, test/foundry/modules/royalty/RoyaltyModule.t.sol
Adds a expiration restriction to royalty payments - preventing those payments past the expiration time.
=> Add expiration restriction on royalty payment

contracts/interfaces/modules/dispute/policies/UMA/IArbitrationPolicyUMA.sol, contracts/modules/dispute/policies/UMA/ArbitrationPolicyUMA.sol, script/foundry/utils/DeployHelper.sol, test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
Adds a set UMA oracle function to UMA arbitration policy contract.
=> Add set oracle to UMA arbitration policy

UPGRADES.md
Corrected the typo in the documentation from "deppend" to "depend".
=> fix typo UPGRADES.md

contracts/modules/dispute/policies/UMA/ArbitrationPolicyUMA.sol, test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
Adds `whenNotPaused` modifier to ArbitrationPolicyUMA.sol functions `onRaiseDispute()`, `disputeAssertion()` and `assertionResolvedCallback()`.
=> Add whenNotPaused modifier to ArbitrationPolicyUMA.sol

contracts/modules/dispute/DisputeModule.sol
Add named arguments to mappings in DisputeModule.sol.
=> Add named arguments to mappings in DisputeModule.sol

contracts/IPAccountImpl.sol, contracts/lib/Errors.sol, contracts/modules/royalty/RoyaltyModule.sol, contracts/modules/royalty/policies/LAP/RoyaltyPolicyLAP.sol, contracts/modules/royalty/policies/LRP/RoyaltyPolicyLRP.sol, contracts/registries/LicenseRegistry.sol
Replaces existing `require()` statements with `Error()`.
=> Fix revert strings

contracts/interfaces/modules/royalty/policies/IIpRoyaltyVault.sol, contracts/interfaces/modules/royalty/policies/IVaultController.sol, contracts/modules/royalty/policies/IpRoyaltyVault.sol, contracts/modules/royalty/policies/VaultController.sol
Changes file license to BUSL on vault controller and ip royalty vault related contracts.
=> Fix file licenses

hardhat.config.ts, test/hardhat/e2e/grouping/group.ipa.test.ts, test/hardhat/e2e/setup.ts, test/hardhat/e2e/utils/licenseHelper.ts, test/hardhat/e2e/utils/mintNFTAndRegisterIPA.ts
Add tests for the grouping module:
- Add tests for creating group IPA
- Add tests for adding IPs to group / removing IPs from group
- Add helper function to register IP license terms
- Add helper function to register IP with license terms
- Load custom errors at global setup
Test result:
- Register Group IPA with whitelisted group pool - Passed
- Register Group IPA with non-whitelisted group pool - Passed
- Add/Remove an IP to the group - Passed
- Add/Remove multiple IPs to the group - Passed
- Non-owner add IP to the group - Passed
- Non-owner remove IP from the group - Passed
- Add IP with none/different license term to the group - Passed
=> add grouping IPA tests

.gitignore, docs/DEPLOY_GUIDE.md, script/foundry/deployment/Main.s.sol
This PR creates a new `docs` folder and adds documentation for deploying the PoC protocol.
=> docs: add protocol deployment guide

CHANGELOG.md, contracts/interfaces/IGroupNFT.sol, contracts/interfaces/modules/licensing/ILicenseTemplate.sol, contracts/lib/PILFlavors.sol, docs/DEPLOY_GUIDE.md, test/hardhat/e2e/permission/permission.test.ts
This pull request resolves several typographical errors in comments and updates broken links to ensure the documentation is accurate and functional. The following changes have been made:
1. **`ILicenseTemplate.sol`**:
- Corrected "an unique" to "a unique."
2. **`IGroupNFT.sol`**:
- Changed "a IP Group" to "an IP Group."
3. **`permission.test.ts`**:
- Fixed "an signer" to "a signer."
4. **`CHANGELOG.md`**:
- Updated comparison links for versions `v1.0.0...v1.1.0` and `v1.0.0-rc.1...v1.0.0` to point to valid URLs:
- [v1.0.0...v1.1.0](https://github.com/storyprotocol/protocol-core-v1/compare/v1.0.0...v1.1.0)
- [v1.0.0-rc.1...v1.0.0](https://github.com/storyprotocol/protocol-core-v1/compare/v1.0.0-rc.1...v1.0.0)
5. **`PILFlavors.sol`**:
- Updated licensing preset flavor links to the new …
=> Fix typographical errors and update broken links in Documentation and Comments

script/foundry/utils/upgrades/UpgradeExecutor.s.sol
changed made:
acumulator - accumulator
=> Fixing Typographical Errors in Documentation

test/foundry/mocks/IMockAncillary.sol, test/foundry/modules/dispute/policies/UMA/ArbitrationPolicyUMA.t.sol
Updates UMA arbitration policy unit tests to latest chain.
=> Update UMA arbitration policy unit tests to latest chain

script/foundry/utils/upgrades/UpgradeExecutor.s.sol
This PR refactors the `UpgradeExecutor` contract to improve its reusability by:
1. Converting modifiers to internal virtual methods that can be overridden by child contracts
2. Making key functions virtual to enable customization in derived implementations 
3. Updating import paths to be more maintainable
4. Removing unused variables and dependencies
- Converted the `onlyMatchingAccessManager` modifier to a virtual internal function `_checkMatchingAccessManager`, enabling derived contracts to customize access checking logic
- Made `_getExecutionData` virtual, allowing child contracts to override implementation-specific upgrade data generation
- Used relative import paths with the `../../../../contracts/` prefix for better consistency
- Removed unused `CREATE3_DEFAULT_SEED` constant and …
=> feat(upgrade): enhance `UpgradeExecutor` contract reusability

test/hardhat/e2e/dispute/dispute.test.ts
This pr enhances dispute tests: add assertions for event emissions
=> Enhance dispute tests: add assertions for event emissions

script/foundry/upgrades/UpgradeDeployer.1.3.2.s.sol, script/foundry/upgrades/UpgradeExecutor.1.3.2.s.sol
- Adds .example upgrade scripts
- Renames existing scripts for the 1.3.2 version
=> Refactor upgrade scripts

test/hardhat/e2e/license/attachLicenseTerms.test.ts, test/hardhat/e2e/license/licenseToken.test.ts
This pr adds e2e tests, includes：
- licenseToken - transfer license token
- LicensingModule - attachDefaultLicenseTerms
Run all e2e tests - `npx hardhat test --network internal_devnet`
=>  Add e2e tests

.github/workflows/foundry_runScript.yml
=> fix secrets

.github/workflows/foundry_runScript.yml
rpc: 'https://aeneid.storyrpc.io/'
=> gha adjustments

.github/workflows/foundry_runScript.yml, hardhat.config.ts
rpc: 'https://aeneid.storyrpc.io/'
=> Upgrade v101.0.0

script/hardhat/utils/safePropose.ts
rpc: 'https://aeneid.storyrpc.io/'
=> Upgrade v102.0.0

.github/workflows/foundry_runScript.yml
chainid: '1315'
operation: 'schedule'
previous version: '1.5.0'
new version: '1.5.1'
=> adjust restriction

.github/workflows/foundry_runScript.yml
chainid: '1315'
operation: 'schedule'
previous version: '1.5.0'
new version: '1.5.1'
=> upgrade-v103.0.0

test/foundry/modules/grouping/EvenSplitGroupPool.t.sol, test/foundry/modules/grouping/GroupingModule.t.sol
This PR adds missing test cases for the grouping functionality, specifically covering GroupingModule.sol and EvenSplitGroupPool.sol to improve test coverage and ensure reliability.
- test_GroupingModule_registerGroup_revert_ZeroGroupRewardPool(): Validates rejection of zero address group reward pools
- test_GroupingModule_claimReward_revert_TokenNotMatchGroupRevenueToken(): Tests error handling when claiming rewards with mismatched tokens
- test_EvenSplitGroupPool_AddIp_revert_EvenSplitGroupPool__MaxGroupSizeReached(): Verifies group size limit enforcement 
- test_EvenSplitGroupPool_depositReward_revert_TokenNotMatchGroupRevenueToken(): Tests token mismatch validation during reward deposits
- test_EvenSplitGroupPool_getAvailableReward_ipNotAdded(): Validates reward calculation for …
=> Add tests to grouping module

test/foundry/access/AccessController.t.sol
This PR introduces a suite of tests for the `setBatchTransientPermissions` functionality in the AccessController contract. The new tests cover:
- Successful setting and checking of batch transient permissions by the IP account owner.
- Reverts when:
- A non-owner attempts to set batch transient permissions.
- The batch includes a zero IP account address or zero signer address.
- The batch includes an invalid IP account or invalid permission value.
- The caller is not the IP account or its owner.
=> Add tests for batch transient permission setter
